name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
    types: [ opened ]   

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: CocoaPods
      run: |
        gem install xcpretty -N
        make init
    - name: Force xcode 11
      run: |
        sudo xcode-select -switch /Applications/Xcode_11.2.1.app
    - name: Build
      run: |
        set -o pipefail
        xcodebuild clean build-for-testing -sdk iphonesimulator -workspace TextFieldsCatalog.xcworkspace -scheme TextFieldsCatalog CODE_SIGNING_REQUIRED=NO | xcpretty -c
    - name: Test
      run: |
        xcodebuild test-without-building -sdk iphonesimulator -workspace TextFieldsCatalog.xcworkspace -scheme TextFieldsCatalog CODE_SIGNING_REQUIRED=NO | xcpretty -c
        
